# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-validate-json

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - master
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - master

jobs:
  verify:
    # NOTE: This name appears in GitHub's Checks API.
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: Validate JSON
      # You may pin to the exact commit or the version.
      # uses: OrRosenblatt/validate-json-action@a7082767d95a588f79b1d742a835b11bbfd4ea32
      uses: OrRosenblatt/validate-json-action@0.1.0
      with:
        # Relative file path under the repository of a JSON schema file to validate the other JSON files with.
        schema: /validators/list.json # default is ./schema.json
        # One or more relative file paths under the repository (seperated by comma) of the JSON files to validate with the schema provided.
        json: 
