name: Check JSON syntax

on:
  push:
    branches: [master]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate JSON
        run: |
          npm install -g jsonlint
          jsonlint -q validators/list.json
