name: Validate JSON on PR

on:
  pull_request:
    branches: [master]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate JSON files
        run: |
          npm install -g jsonlint
          for file in $(find . -name "*.json"); do
            if jsonlint -q $file; then
              echo "Validation successful: $file"
            else
              echo "Validation failed: $file"
              exit 1
            fi
          done
      - name: Comment on PR if failed
        if: failure()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The following JSON files failed validation:\n' + $(find . -name '*.json' -type f -printf '\n- %p')
            })
