name: Validate JSON Syntax
on: [push, pull_request]

jobs:
  json_syntax_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate JSON Syntax
        run: |
          if ! curl -s https://raw.githubusercontent.com/aurowallet/launch/master/validators/list.json | jq empty 2>&1 >/dev/null; then
            echo "JSON syntax check failed"
            exit 1
          fi
